version: "3.8"
services:
    service1:
        container_name: service1
        build: ./service1
        image: raihan95/service1:latest
        ports:
            - target: 5000
              published: 5000
              protocol: tcp

    service2:
        container_name: service2
        build: ./service2
        image: raihan95/service2:latest
        ports:
            - target: 5001
              published: 5001
              protocol: tcp
    
    service3:
        container_name: service3
        build: ./service3
        image: raihan95/service3:latest
        ports:
            - target: 5002
              published: 5002
              protocol: tcp

    service4:
        container_name: service4
        build: ./service4
        image: raihan95/service4:latest
        ports:
            - target: 5003
              published: 5003
              protocol: tcp
