version: "3.8"
services:
    service1:
        container_name: service1
        build: ./service1
        image: service1:latest
        ports:
            - target: 5001
              published: 5001
              protocol: tcp
    
    service2:
        container_name: service2
        build: ./service2
        image: service2:latest
        ports:
            - target: 5002
              protocol: tcp
    
    service3:
        container_name: service3
        build: ./service3
        image: service3:latest
        ports:
            - target: 5003
              protocol: tcp

    service4:
        container_name: service4
        build: ./service4
        image: service4:latest
        ports:
            - target: 5004
              protocol: tcp
