all:
  children:
    managers:
      hosts:
        manager:
    workers:
      hosts:
        worker-one:
        worker-two:
  vars:
    ansible_user: jenkins
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_users:
      - username: jenkins
      - username: raihan

  hosts:
    nginx: