all:
  children:
    manager:
      hosts:
        manager:
    worker:
      hosts:
        worker-one: # worker-one is the vm name public or private ip can also be used.
        worker-two:
    nginx:
      hosts: 
        nginx:
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  #   ansible_user: jenkins
  #   ansible_ssh_private_key_file: '~/.ssh/id_rsa'